// ==========================================
// SKILL Forge 技能工厂 API
// ==========================================

import { fetchAPI, BASE_URL } from '../api';
import { cachedFetch, invalidateCache } from '../apiCache';

export type ExecutorType = 'Python_env' | 'R_env' | 'Logical_Blueprint' | 'Python_Package';

export interface CraftRequest {
  raw_material: string;
  executor_type?: ExecutorType;
  generate_full_bundle?: boolean;
  skill_name_hint?: string;
  category?: string;
  subcategory?: string;
  tags?: string[];
}

export interface CraftResponse {
  name: string;
  description: string;
  executor_type: ExecutorType;
  parameters_schema: Record<string, any>;
  expert_knowledge: string;
  script_code?: string;
  nextflow_code?: string;
  dependencies: string[];
  validation_warning?: string;
  validation_passed?: boolean;
  skill_md?: string;
}

export interface BundleResponse {
  status: string;
  skill_id: string;
  name: string;
  bundle_path: string;
  files_created: string[];
  executor_type: ExecutorType;
  message: string;
}

export interface SkillAsset {
  id: number;
  skill_id: string;
  name: string;
  description: string | null;
  version: string;
  executor_type: string;
  parameters_schema: Record<string, any>;
  expert_knowledge: string | null;
  script_code: string | null;
  nextflow_code: string | null;
  dependencies: string[];
  status: string;
  reject_reason: string | null;
  owner_id: number;
  // 分类信息
  category: string | null;
  category_name: string | null;
  subcategory: string | null;
  subcategory_name: string | null;
  tags: string[];
  // 基础分析标记
  is_basic_analysis: boolean;
  created_at: string;
  updated_at: string;
}

export const skillForgeApi = {
  /**
   * 获取当前用户可用的所有技能（已包含权限过滤）
   * 使用缓存优化，缓存 5 分钟
   */
  listSkills: async (options?: { forceRefresh?: boolean }): Promise<SkillAsset[]> => {
    return cachedFetch<SkillAsset[]>(
      'skills:list',
      () => fetchAPI('/api/skills/'),
      undefined,
      options
    );
  },

  /**
   * 使技能列表缓存失效
   */
  invalidateSkillsCache: () => {
    invalidateCache('skills:list');
  },

  /**
   * 将非结构化素材发送给大脑进行锻造
   */
  craftFromMaterial: async (request: CraftRequest): Promise<{
    data: CraftResponse;
    bundle_path?: string;
    files_created?: string[];
  }> => {
    const response = await fetchAPI('/api/skills/craft_from_material', {
      method: 'POST',
      body: JSON.stringify({
        raw_material: request.raw_material,
        executor_type: request.executor_type || 'Python_env',
        generate_full_bundle: request.generate_full_bundle || false,
        skill_name_hint: request.skill_name_hint,
        category: request.category,
        subcategory: request.subcategory,
        tags: request.tags || []
      }),
    });
    return response;
  },

  /**
   * 直接创建完整文件系统技能包
   */
  createSkillBundle: async (request: CraftRequest): Promise<BundleResponse> => {
    const response = await fetchAPI('/api/skills/bundle', {
      method: 'POST',
      body: JSON.stringify({
        raw_material: request.raw_material,
        executor_type: request.executor_type || 'Python_env',
        skill_name_hint: request.skill_name_hint,
        category: request.category,
        subcategory: request.subcategory,
        tags: request.tags || []
      }),
    });
    return response;
  },

  /**
   * 从压缩包创建技能
   * 支持 .zip, .tar.gz, .tgz 格式
   */
  craftFromBundle: async (params: {
    file: File;
    executorType?: ExecutorType;
    skillNameHint?: string;
    generateFullBundle?: boolean;
    category?: string;
    tags?: string[];
  }): Promise<{
    data: CraftResponse;
    bundle_path?: string;
    files_created?: string[];
    parsed_files?: Array<{
      path: string;
      type: string;
      language: string | null;
      size: number;
      preview: string;
    }>;
    file_stats?: Record<string, number>;
    raw_material_length?: number;
  }> => {
    const formData = new FormData();
    formData.append('file', params.file);
    formData.append('executor_type', params.executorType || 'Logical_Blueprint');
    formData.append('generate_full_bundle', String(params.generateFullBundle !== false));
    if (params.skillNameHint) {
      formData.append('skill_name_hint', params.skillNameHint);
    }
    if (params.category) {
      formData.append('category', params.category);
    }
    formData.append('tags', JSON.stringify(params.tags || []));

    const response = await fetchAPI('/api/skills/craft_from_bundle', {
      method: 'POST',
      body: formData,
    });
    return response;
  },

  /**
   * 测试草稿技能（增强版）
   * 支持自动生成测试数据、多场景测试、自动修复
   */
  testDraftSkill: async (params: {
    scriptCode: string;
    testInstruction?: string;
    parametersSchema?: Record<string, any>;
    autoGenerateData?: boolean;
    maxTestRounds?: number;
    executorType?: string;
  }): Promise<any> => {
    const response = await fetchAPI('/api/skills/test_draft', {
      method: 'POST',
      body: JSON.stringify({
        script_code: params.scriptCode,
        test_instruction: params.testInstruction || '',
        parameters_schema: params.parametersSchema,
        auto_generate_data: params.autoGenerateData !== false,
        max_test_rounds: params.maxTestRounds || 3,
        executor_type: params.executorType || 'Python_env'
      }),
    });
    return response.data;
  },

  /**
   * 测试草稿技能（SSE 流式日志版本）
   * 实时返回测试进度，支持前端实时显示
   * 支持超时取消机制
   */
  testDraftSkillStream: async (
    params: {
      scriptCode: string;
      testInstruction?: string;
      parametersSchema?: Record<string, any>;
      autoGenerateData?: boolean;
      maxTestRounds?: number;
      executorType?: string;
    },
    onLog: (message: string) => void,
    onStatus?: (status: string) => void,
    onResult?: (result: any) => void,
    onFileItem?: (file: { name: string; path: string; size: number; type: string }) => void,
    signal?: AbortSignal // 可选的外部取消信号
  ): Promise<void> => {
    const token = localStorage.getItem('autonome_access_token');
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }

    // 创建 AbortController 用于超时控制
    const controller = new AbortController();
    const timeoutMs = 600000; // 10分钟总超时
    const inactivityTimeoutMs = 180000; // 3分钟无活动超时（适应LLM生成测试数据）

    const timeoutId = setTimeout(() => {
      controller.abort();
      onLog('测试超时（10分钟），已自动取消');
    }, timeoutMs);

    // 合并外部信号
    if (signal) {
      signal.addEventListener('abort', () => {
        controller.abort();
        onLog('测试已取消');
      });
    }

    try {
      const response = await fetch(`${BASE_URL}/api/skills/test_draft_stream`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          script_code: params.scriptCode,
          test_instruction: params.testInstruction || '',
          parameters_schema: params.parametersSchema,
          auto_generate_data: params.autoGenerateData !== false,
          max_test_rounds: params.maxTestRounds || 3,
          executor_type: params.executorType || 'Python_env'
        }),
        signal: controller.signal,
      });

      if (!response.ok) {
        throw new Error(`测试请求失败: ${response.status}`);
      }

      const reader = response.body?.getReader();
      if (!reader) {
        throw new Error('无法获取响应流');
      }

      const decoder = new TextDecoder();
      let buffer = '';
      let lastActivity = Date.now();

      // 无活动超时检测
      const inactivityCheck = setInterval(() => {
        if (Date.now() - lastActivity > inactivityTimeoutMs) {
          controller.abort();
          onLog('响应超时（3分钟无活动），已自动取消');
        }
      }, 10000);

      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          lastActivity = Date.now(); // 更新活动时间

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split('\n');
          buffer = lines.pop() || '';

          for (const line of lines) {
            if (line.startsWith('data: ')) {
              try {
                const event = JSON.parse(line.slice(6));

                // 心跳事件不触发回调
                if (event.type === 'heartbeat') continue;

                if (event.type === 'log' && event.message) {
                  onLog(event.message);
                } else if (event.type === 'status' && onStatus) {
                  onStatus(event.message);
                } else if (event.type === 'result' && onResult) {
                  onResult(event.data);
                } else if (event.type === 'file_tree' && event.message) {
                  onLog(event.message);
                } else if (event.type === 'file_item' && onFileItem && event.data) {
                  onFileItem(event.data);
                }
              } catch (e) {
                // 忽略解析错误
              }
            }
          }
        }
      } finally {
        clearInterval(inactivityCheck);
        reader.releaseLock();
      }
    } catch (error: any) {
      if (error.name === 'AbortError') {
        onLog('测试已取消');
      } else {
        throw error;
      }
    } finally {
      clearTimeout(timeoutId);
    }
  },

  /**
   * 保存为私有技能 (入库)
   */
  savePrivateSkill: async (skillData: Partial<SkillAsset>): Promise<SkillAsset> => {
    const response = await fetchAPI('/api/skills/', {
      method: 'POST',
      body: JSON.stringify(skillData),
    });
    return response;
  },

  /**
   * 获取单个技能详情
   */
  getSkill: async (skillId: string): Promise<any> => {
    const response = await fetchAPI(`/api/skills/${skillId}`);
    // 后端返回 { status: "success", source: "database/filesystem", data: { ... } }
    // 需要提取 data 字段
    return response.data || response;
  },

  /**
   * 更新技能
   */
  updateSkill: async (skillId: string, skillData: Partial<SkillAsset>): Promise<SkillAsset> => {
    const response = await fetchAPI(`/api/skills/${skillId}`, {
      method: 'PUT',
      body: JSON.stringify(skillData),
    });
    return response;
  },

  /**
   * 删除技能
   */
  deleteSkill: async (skillId: string): Promise<any> => {
    const response = await fetchAPI(`/api/skills/${skillId}`, {
      method: 'DELETE',
    });
    return response;
  },

  /**
   * 提交给管理员审核
   */
  submitForReview: async (skillId: string): Promise<any> => {
    const response = await fetchAPI(`/api/skills/${skillId}/submit_review`, {
      method: 'POST',
    });
    return response;
  },

  /**
   * 获取技能目录（包含文件系统和数据库）
   */
  getCatalog: async (): Promise<any> => {
    const response = await fetchAPI('/api/skills/catalog');
    return response;
  },

  /**
   * 获取我的技能列表
   */
  listMySkills: async (status?: string): Promise<SkillAsset[]> => {
    const params = status ? `?status=${status}` : '';
    const response = await fetchAPI(`/api/skills/my${params}`);
    return response;
  },

  /**
   * 获取技能版本历史
   */
  getVersions: async (skillId: string): Promise<{ status: string; total: number; data: any[] }> => {
    const response = await fetchAPI(`/api/skills/${skillId}/versions`);
    return response;
  },

  /**
   * 创建新版本
   */
  createVersion: async (skillId: string, version: string, changeLog?: string): Promise<any> => {
    const params = new URLSearchParams({ version });
    if (changeLog) params.append('change_log', changeLog);
    const response = await fetchAPI(`/api/skills/${skillId}/versions?${params.toString()}`, {
      method: 'POST',
    });
    return response;
  },

  /**
   * 回滚到指定版本
   */
  rollbackVersion: async (skillId: string, versionId: number): Promise<any> => {
    const response = await fetchAPI(`/api/skills/${skillId}/rollback/${versionId}`, {
      method: 'POST',
    });
    return response;
  },

  /**
   * 获取技能使用统计
   */
  getStats: async (skillId: string): Promise<any> => {
    const response = await fetchAPI(`/api/skills/${skillId}/stats`);
    return response;
  },

  /**
   * 获取技能执行历史
   */
  getExecutionHistory: async (skillId: string, limit: number = 20): Promise<any> => {
    const response = await fetchAPI(`/api/skills/${skillId}/history?limit=${limit}`);
    return response;
  }
};
