"use client";

import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import ReactECharts from 'echarts-for-react';
import { Copy, Check } from 'lucide-react';

import { DatasetCards } from "./chat/DatasetCards";

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://113.44.66.210:8000';

function getImageUrl(src: string | Blob | undefined): string {
  if (!src || typeof src !== 'string') return '';
  if (src.startsWith('http://') || src.startsWith('https://')) {
    return src;
  }
  const token = typeof window !== 'undefined' ? localStorage.getItem('autonome_access_token') : '';
  return `${API_URL}${src}?token=${token}`;
}

export function MarkdownBlock({ content }: { content: string }) {
  return (
    <div className="prose prose-invert prose-sm max-w-none prose-pre:p-0 prose-pre:bg-transparent">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          img: ({ src, alt }) => {
            const srcUrl = getImageUrl(src);
            return (
              <img 
                src={srcUrl} 
                className="max-w-full max-h-96 my-4 rounded-lg border border-neutral-700 hover:opacity-90 transition-opacity shadow-lg"
                alt={alt || "Analysis Chart"}
              />
            );
          },

          code({ className, children, ...props }) {
            const match = /language-(\w+)/.exec(className || '');
            const [copied, setCopied] = useState(false);
            
            const handleCopy = () => {
              const codeString = String(children).replace(/\n$/, '');
              navigator.clipboard.writeText(codeString);
              setCopied(true);
              setTimeout(() => setCopied(false), 2000);
            };
            
            if (!match) {
              return (
                <code className="bg-neutral-800 text-blue-400 px-1.5 py-0.5 rounded text-[0.85em] font-mono" {...props}>
                  {children}
                </code>
              );
            }
            
            const lang = match[1];
            
            if (lang === 'echarts') {
              try {
                const echartOption = JSON.parse(String(children));
                return (
                  <div className="my-6 bg-[#101010] p-4 rounded-xl border border-neutral-800 shadow-2xl overflow-hidden">
                    <div className="flex items-center justify-between mb-2 pb-2 border-b border-neutral-800 text-xs text-neutral-500 font-mono">
                      <span>📊 Interactive Chart Generated by AI</span>
                    </div>
                    <ReactECharts 
                      option={echartOption} 
                      theme="dark" 
                      style={{ height: '400px', width: '100%', backgroundColor: 'transparent' }} 
                    />
                  </div>
                );
              } catch {
                return (
                  <div className="my-4 border border-red-900/50 bg-red-950/20 rounded-md p-4">
                    <p className="text-red-500 text-xs mb-2">⚠️ Chart JSON parsing failed, showing source:</p>
                    <pre className="text-neutral-400 text-xs overflow-x-auto">{String(children)}</pre>
                  </div>
                );
              }
            }

            if (lang === 'dataset_cards') {
              try {
                const datasets = JSON.parse(String(children).replace(/\n$/, ""));
                return <DatasetCards datasets={datasets} />;
              } catch {
                return (
                  <div className="p-4 bg-red-950/30 text-red-400 border border-red-900/50 rounded-lg text-xs font-mono">
                    ⚠️ 数据解析失败：大模型返回的 JSON 格式有误。
                  </div>
                );
              }
            }

            return (
              <div className="relative group my-4">
                <button
                  onClick={handleCopy}
                  className="absolute right-2 top-2 p-1.5 rounded-md bg-neutral-800 border border-neutral-700 text-neutral-400 opacity-0 group-hover:opacity-100 transition-opacity z-10 hover:text-white hover:bg-neutral-700"
                  title="复制代码"
                >
                  {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                </button>
                <SyntaxHighlighter
                  style={vscDarkPlus}
                  language={lang}
                  PreTag="div"
                  customStyle={{
                    margin: 0,
                    borderRadius: '0.75rem',
                    fontSize: '0.875rem',
                    lineHeight: '1.5',
                    whiteSpace: 'pre-wrap',
                    wordBreak: 'break-all',
                    background: '#0a0a0a',
                  }}
                >
                  {String(children).replace(/\n$/, '')}
                </SyntaxHighlighter>
              </div>
            );
          },
          table({ children }) {
            return <div className="overflow-x-auto my-4 border border-neutral-800 rounded-lg"><table className="min-w-full divide-y divide-neutral-800">{children}</table></div>;
          },
          th({ children }) {
            return <th className="px-4 py-2 bg-neutral-900/50 text-left text-xs font-medium text-neutral-300 uppercase tracking-wider border-b border-neutral-800">{children}</th>;
          },
          td({ children }) {
            return <td className="px-4 py-2 whitespace-nowrap text-sm text-neutral-400 border-b border-neutral-800/50">{children}</td>;
          }
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}
