"use client";

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/cjs/styles/prism';
import ReactECharts from 'echarts-for-react';

import { DatasetCards } from "./chat/DatasetCards";

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://113.44.66.210:8000';

function getImageUrl(src: string | Blob | undefined): string {
  if (!src || typeof src !== 'string') return '';
  if (src.startsWith('http://') || src.startsWith('https://')) {
    return src;
  }
  const token = typeof window !== 'undefined' ? localStorage.getItem('autonome_access_token') : '';
  return `${API_URL}${src}?token=${token}`;
}

export function MarkdownBlock({ content }: { content: string }) {
  return (
    <div className="prose prose-invert prose-sm max-w-none prose-pre:p-0 prose-pre:bg-transparent">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          img: ({ node, ...props }) => {
            const srcUrl = getImageUrl(props.src);
            return (
              <img 
                {...props} 
                src={srcUrl} 
                className="max-w-full max-h-96 my-4 rounded-lg border border-neutral-700 hover:opacity-90 transition-opacity shadow-lg"
                alt={props.alt || "Analysis Chart"}
              />
            );
          },

          code({ node, inline, className, children, ...props }: any) {
            const match = /language-(\w+)/.exec(className || '');
            
            if (!inline && match && match[1] === 'echarts') {
              try {
                const echartOption = JSON.parse(String(children));
                return (
                  <div className="my-6 bg-[#101010] p-4 rounded-xl border border-neutral-800 shadow-2xl overflow-hidden">
                    <div className="flex items-center justify-between mb-2 pb-2 border-b border-neutral-800 text-xs text-neutral-500 font-mono">
                      <span>📊 Interactive Chart Generated by AI</span>
                    </div>
                    <ReactECharts 
                      option={echartOption} 
                      theme="dark" 
                      style={{ height: '400px', width: '100%', backgroundColor: 'transparent' }} 
                    />
                  </div>
                );
              } catch (error) {
                return (
                  <div className="my-4 border border-red-900/50 bg-red-950/20 rounded-md p-4">
                    <p className="text-red-500 text-xs mb-2">⚠️ Chart JSON parsing failed, showing source:</p>
                    <pre className="text-neutral-400 text-xs overflow-x-auto">{String(children)}</pre>
                  </div>
                );
              }
            }

            if (!inline && match && match[1] === 'dataset_cards') {
              try {
                const datasets = JSON.parse(String(children).replace(/\n$/, ""));
                return <DatasetCards datasets={datasets} />;
              } catch (e) {
                return (
                  <div className="p-4 bg-red-950/30 text-red-400 border border-red-900/50 rounded-lg text-xs font-mono">
                    ⚠️ 数据解析失败：大模型返回的 JSON 格式有误。
                  </div>
                );
              }
            }

            return !inline && match ? (
              <div className="rounded-md overflow-hidden border border-neutral-700 my-4 shadow-lg">
                <div className="bg-neutral-800 px-4 py-1 text-xs text-neutral-400 font-mono border-b border-neutral-700 flex justify-between items-center">
                  <span>{match[1]}</span>
                  <button className="hover:text-white transition-colors">Copy</button>
                </div>
                <SyntaxHighlighter
                  {...props}
                  style={vscDarkPlus}
                  language={match[1]}
                  PreTag="div"
                  customStyle={{ margin: 0, padding: '1rem', background: '#0a0a0a' }}
                >
                  {String(children).replace(/\n$/, '')}
                </SyntaxHighlighter>
              </div>
            ) : (
              <code {...props} className="bg-neutral-800 text-blue-400 px-1.5 py-0.5 rounded text-[0.85em] font-mono">
                {children}
              </code>
            );
          },
          table({ children }) {
            return <div className="overflow-x-auto my-4 border border-neutral-800 rounded-lg"><table className="min-w-full divide-y divide-neutral-800">{children}</table></div>;
          },
          th({ children }) {
            return <th className="px-4 py-2 bg-neutral-900/50 text-left text-xs font-medium text-neutral-300 uppercase tracking-wider border-b border-neutral-800">{children}</th>;
          },
          td({ children }) {
            return <td className="px-4 py-2 whitespace-nowrap text-sm text-neutral-400 border-b border-neutral-800/50">{children}</td>;
          }
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}
