"""
任务元数据文件生成器

自动生成两个"元数据烙印"文件：
1. run_parameters.tsv - 运行参数日志（TSV 格式）
2. README_autonome.md - 程序说明与溯源文档

设计原则：
- 确保分析结果的可复现性
- 即使脱离 Autonome 平台也能理解数据来源
- 方便下游流程读取或重新执行
"""

import os
from datetime import datetime
from typing import Any, Dict, List, Optional, Union
from app.core.logger import log


# ============================================================================
# 常量定义
# ============================================================================

# TSV 文件表头
TSV_HEADERS = ["parameter", "value", "type", "source"]

# README 模板
README_TEMPLATE = """# Autonome Analysis Run

> This file was automatically generated by Autonome Studio.
> It contains all the information needed to reproduce this analysis.

---

## 📋 Task Information

| Field | Value |
|-------|-------|
| **Task ID** | {task_id} |
| **Semantic Dir** | {semantic_dir_name} |
| **Skill** | {skill_name} |
| **Executor Type** | {executor_type} |
| **Timestamp** | {timestamp} |
| **Project ID** | {project_id} |

---

## 🎯 Original User Intent

```
{user_message}
```

---

## ⚙️ Execution Details

| Component | Details |
|-----------|---------|
| **Docker Image** | {docker_image} |
| **Entry Point** | {entry_point} |
| **Execution Mode** | {execution_mode} |
| **Duration** | {duration} |

---

## 📊 Parameters

| Parameter | Value | Type |
|-----------|-------|------|
{parameters_table}

---

## 📁 Input/Output

| Type | Path |
|------|------|
{io_table}

---

## 🔧 Reproduction

To reproduce this analysis:

```bash
# Clone the skill repository
git clone {skill_repo}

# Run with Docker
docker run --rm \\
  -v $(pwd)/data:/data \\
  -v $(pwd)/results:/results \\
  {docker_image} \\
  python {entry_point} {cli_args}
```

---

## 📜 License & Attribution

- **Skill License**: {skill_license}
- **Generated by**: Autonome Studio v{version}
- **Generated at**: {generated_at}

---

*This file ensures **Full Reproducibility** of the analysis.*
"""


# ============================================================================
# 核心函数：生成 run_parameters.tsv
# ============================================================================

def generate_run_parameters_tsv(
    output_path: str,
    parameters: Dict[str, Any],
    execution_context: Dict[str, Any],
    skill_metadata: Optional[Dict[str, Any]] = None,
) -> str:
    """
    生成 run_parameters.tsv 文件

    Args:
        output_path: 输出文件路径
        parameters: 用户输入参数
        execution_context: 执行上下文（task_id, project_id, timestamp 等）
        skill_metadata: 技能元数据（可选）

    Returns:
        生成的文件路径

    TSV Format:
        parameter    value    type    source
        sample_sheet    ./sample.tsv    filepath    user_input
        threads    8    integer    config
    """
    rows: List[List[str]] = [TSV_HEADERS]

    # 1. 添加执行上下文
    context_rows = _format_context_rows(execution_context)
    rows.extend(context_rows)

    # 2. 添加用户参数
    param_rows = _format_parameter_rows(parameters)
    rows.extend(param_rows)

    # 3. 添加技能元数据
    if skill_metadata:
        skill_rows = _format_skill_rows(skill_metadata)
        rows.extend(skill_rows)

    # 写入文件
    _write_tsv(output_path, rows)

    log.info(f"Generated run_parameters.tsv: {output_path}")
    return output_path


def _format_context_rows(context: Dict[str, Any]) -> List[List[str]]:
    """格式化执行上下文为 TSV 行"""
    rows = []

    # 标准上下文字段
    context_fields = [
        ("Task_ID", context.get("task_id", ""), "string", "system"),
        ("Semantic_Dir", context.get("semantic_dir_name", ""), "string", "system"),
        ("Project_ID", context.get("project_id", ""), "string", "system"),
        ("Execution_Time", context.get("timestamp", ""), "datetime", "system"),
        ("Duration_Seconds", context.get("duration", ""), "integer", "system"),
    ]

    for param, value, ptype, source in context_fields:
        if value:
            rows.append([param, str(value), ptype, source])

    return rows


def _format_parameter_rows(parameters: Dict[str, Any]) -> List[List[str]]:
    """格式化用户参数为 TSV 行"""
    rows = []

    for key, value in parameters.items():
        # 跳过内部参数
        if key.startswith("_") or key in ["message", "user_message"]:
            continue

        # 推断类型
        ptype = _infer_type(value)
        source = "user_input"

        # 处理特殊值
        if isinstance(value, (list, dict)):
            value = str(value)[:200]  # 截断长值
        elif value is None:
            continue

        rows.append([key, str(value), ptype, source])

    return rows


def _format_skill_rows(metadata: Dict[str, Any]) -> List[List[str]]:
    """格式化技能元数据为 TSV 行"""
    rows = []

    skill_fields = [
        ("Skill_ID", metadata.get("skill_id", ""), "string", "skill"),
        ("Skill_Name", metadata.get("name", ""), "string", "skill"),
        ("Skill_Version", metadata.get("version", ""), "string", "skill"),
        ("Executor_Type", metadata.get("executor_type", ""), "string", "skill"),
        ("Entry_Point", metadata.get("entry_point", ""), "string", "skill"),
        ("Docker_Image", metadata.get("docker_image", ""), "string", "skill"),
    ]

    for param, value, ptype, source in skill_fields:
        if value:
            rows.append([param, str(value), ptype, source])

    return rows


def _infer_type(value: Any) -> str:
    """推断参数类型"""
    if isinstance(value, bool):
        return "boolean"
    elif isinstance(value, int):
        return "integer"
    elif isinstance(value, float):
        return "float"
    elif isinstance(value, str):
        # 检查是否是文件路径
        if "/" in value or value.startswith("./") or value.endswith((".tsv", ".csv", ".fastq", ".bam")):
            return "filepath"
        return "string"
    elif isinstance(value, list):
        return "array"
    elif isinstance(value, dict):
        return "object"
    return "unknown"


def _write_tsv(path: str, rows: List[List[str]]) -> None:
    """写入 TSV 文件"""
    # 确保目录存在
    os.makedirs(os.path.dirname(path), exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            # TSV 使用制表符分隔
            line = "\t".join(row)
            f.write(line + "\n")


# ============================================================================
# 核心函数：生成 README_autonome.md
# ============================================================================

def generate_readme_autonome_md(
    output_path: str,
    task_id: str,
    skill_name: str,
    user_message: str,
    docker_image: str,
    entry_point: str,
    parameters: Dict[str, Any],
    timestamp: Union[str, datetime],
    semantic_dir_name: Optional[str] = None,
    project_id: Optional[str] = None,
    executor_type: str = "Python_env",
    duration: Optional[float] = None,
    skill_repo: Optional[str] = None,
    skill_license: str = "MIT",
    version: str = "1.0.0",
    input_paths: Optional[List[str]] = None,
    output_paths: Optional[List[str]] = None,
) -> str:
    """
    生成 README_autonome.md 文件

    Args:
        output_path: 输出文件路径
        task_id: 任务 ID
        skill_name: 技能名称
        user_message: 用户原始意图
        docker_image: Docker 镜像名称
        entry_point: 入口脚本
        parameters: 执行参数
        timestamp: 执行时间
        semantic_dir_name: 语义化目录名
        project_id: 项目 ID
        executor_type: 执行器类型
        duration: 执行时长（秒）
        skill_repo: 技能仓库地址
        skill_license: 技能许可证
        version: Autonome 版本
        input_paths: 输入文件路径列表
        output_paths: 输出文件路径列表

    Returns:
        生成的文件路径
    """
    # 格式化时间戳
    if isinstance(timestamp, datetime):
        timestamp_str = timestamp.strftime("%Y-%m-%d %H:%M:%S")
    else:
        timestamp_str = str(timestamp)

    # 格式化执行时长
    if duration:
        duration_str = f"{duration:.2f}s"
    else:
        duration_str = "N/A"

    # 生成参数表格
    parameters_table = _generate_parameters_table(parameters)

    # 生成 IO 表格
    io_table = _generate_io_table(input_paths, output_paths)

    # 生成 CLI 参数
    cli_args = _generate_cli_args(parameters)

    # 生成 README 内容
    content = README_TEMPLATE.format(
        task_id=task_id,
        semantic_dir_name=semantic_dir_name or task_id[:8],
        skill_name=skill_name,
        executor_type=executor_type,
        timestamp=timestamp_str,
        project_id=project_id or "N/A",
        user_message=user_message or "No user message provided",
        docker_image=docker_image,
        entry_point=entry_point,
        execution_mode=executor_type,
        duration=duration_str,
        parameters_table=parameters_table,
        io_table=io_table,
        skill_repo=skill_repo or "https://github.com/autonome/skills",
        cli_args=cli_args,
        skill_license=skill_license,
        version=version,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )

    # 写入文件
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    log.info(f"Generated README_autonome.md: {output_path}")
    return output_path


def _generate_parameters_table(parameters: Dict[str, Any]) -> str:
    """生成 Markdown 参数表格"""
    rows = []
    for key, value in parameters.items():
        if key.startswith("_") or key in ["message", "user_message"]:
            continue
        if value is None:
            continue

        ptype = _infer_type(value)
        value_str = str(value)[:100]  # 截断长值

        rows.append(f"| `{key}` | `{value_str}` | {ptype} |")

    return "\n".join(rows) if rows else "| - | - | - |"


def _generate_io_table(
    input_paths: Optional[List[str]],
    output_paths: Optional[List[str]],
) -> str:
    """生成 Markdown IO 表格"""
    rows = []

    if input_paths:
        for path in input_paths:
            rows.append(f"| Input | `{path}` |")

    if output_paths:
        for path in output_paths:
            rows.append(f"| Output | `{path}` |")

    return "\n".join(rows) if rows else "| - | - |"


def _generate_cli_args(parameters: Dict[str, Any]) -> str:
    """生成 CLI 参数字符串"""
    args = []
    for key, value in parameters.items():
        if key.startswith("_") or key in ["message", "user_message", "PROJECT_ID", "TASK_ID"]:
            continue
        if value is None:
            continue

        # 格式化为 --key value
        key_arg = key.replace("_", "-")
        args.append(f"--{key_arg} {value}")

    return " \\\n  ".join(args) if args else ""


# ============================================================================
# 便捷函数：一键生成所有元数据文件
# ============================================================================

def inject_metadata_files(
    output_dir: str,
    task_id: str,
    skill_id: str,
    skill_name: str,
    user_message: str,
    parameters: Dict[str, Any],
    docker_image: str,
    entry_point: str,
    timestamp: Union[str, datetime],
    semantic_dir_name: Optional[str] = None,
    project_id: Optional[str] = None,
    executor_type: str = "Python_env",
    duration: Optional[float] = None,
    skill_metadata: Optional[Dict[str, Any]] = None,
    input_paths: Optional[List[str]] = None,
    output_paths: Optional[List[str]] = None,
) -> Dict[str, str]:
    """
    一键生成所有元数据文件

    Args:
        output_dir: 输出目录
        其他参数同上

    Returns:
        生成的文件路径字典
    """
    # 确保输出目录存在
    os.makedirs(output_dir, exist_ok=True)

    # 准备执行上下文
    execution_context = {
        "task_id": task_id,
        "semantic_dir_name": semantic_dir_name,
        "project_id": project_id,
        "timestamp": timestamp,
        "duration": duration,
    }

    # 准备技能元数据
    if skill_metadata is None:
        skill_metadata = {
            "skill_id": skill_id,
            "name": skill_name,
            "executor_type": executor_type,
            "entry_point": entry_point,
            "docker_image": docker_image,
        }

    # 生成 run_parameters.tsv
    tsv_path = os.path.join(output_dir, "run_parameters.tsv")
    generate_run_parameters_tsv(
        output_path=tsv_path,
        parameters=parameters,
        execution_context=execution_context,
        skill_metadata=skill_metadata,
    )

    # 生成 README_autonome.md
    readme_path = os.path.join(output_dir, "README_autonome.md")
    generate_readme_autonome_md(
        output_path=readme_path,
        task_id=task_id,
        skill_name=skill_name,
        user_message=user_message,
        docker_image=docker_image,
        entry_point=entry_point,
        parameters=parameters,
        timestamp=timestamp,
        semantic_dir_name=semantic_dir_name,
        project_id=project_id,
        executor_type=executor_type,
        duration=duration,
        input_paths=input_paths,
        output_paths=output_paths,
    )

    log.info(f"Injected metadata files into: {output_dir}")

    return {
        "run_parameters_tsv": tsv_path,
        "readme_md": readme_path,
    }