"use client";

import React, { useState } from 'react';
import { Play, Code, FileJson, Save, Send, Check, AlertTriangle } from 'lucide-react';

import { useForgeStore } from '@/store/useForgeStore';
import { skillForgeApi, forgeSessionApi } from '@/lib/api';

// 执行器类型配置
const EXECUTOR_TYPES = [
  { value: 'Python_env', label: 'Python 脚本', description: '使用 argparse 参数化' },
  { value: 'R_env', label: 'R 脚本', description: '使用 commandArgs 参数化' },
  { value: 'Logical_Blueprint', label: 'Nextflow 工作流', description: 'DSL2 并行工作流' },
] as const;

export function SkillDraftEditor() {
  const {
    sessionId,
    skillDraft,
    updateSkillDraft,
    setSkillDraft,
    executorType,
    setExecutorType
  } = useForgeStore();

  const [isTesting, setIsTesting] = useState(false);
  const [testLogs, setTestLogs] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'success' | 'error'>('idle');

  // 沙箱测试
  const handleTest = async () => {
    if (!skillDraft.script_code) {
      setTestLogs('没有代码可测试');
      return;
    }

    setIsTesting(true);
    setTestLogs('🚀 正在启动沙箱测试...\n');

    try {
      const result = await skillForgeApi.testDraftSkill({
        scriptCode: skillDraft.script_code,
        parametersSchema: skillDraft.parameters_schema,
        autoGenerateData: true,
        maxTestRounds: 3,
        executorType: executorType
      });

      setTestLogs(result.logs || '测试完成');

      // 如果AI修复了代码，更新
      if (result.final_code && result.final_code !== skillDraft.script_code) {
        updateSkillDraft({ script_code: result.final_code });
        setTestLogs(prev => prev + '\n\n🤖 代码已自动修复');
      }

      if (result.status === 'success') {
        setTestLogs(prev => prev + '\n\n✅ 所有测试通过！');
      } else if (result.status === 'partial') {
        setTestLogs(prev => prev + '\n\n⚠️ 部分测试通过');
      } else {
        setTestLogs(prev => prev + '\n\n❌ 测试失败');
      }
    } catch (error: any) {
      setTestLogs(`❌ 测试失败: ${error.message}`);
    } finally {
      setIsTesting(false);
    }
  };

  // 保存为私有
  const handleSaveOnly = async () => {
    if (!sessionId || !skillDraft.script_code) return;

    setIsSaving(true);
    setSaveStatus('idle');

    try {
      // 先更新草稿
      await forgeSessionApi.updateDraft(sessionId, {
        name: skillDraft.name,
        description: skillDraft.description,
        script_code: skillDraft.script_code,
        parameters_schema: skillDraft.parameters_schema
      });

      // 提交保存
      const result = await forgeSessionApi.commitSkill(sessionId);
      setSaveStatus('success');
      setTestLogs(`✅ 技能已保存！ID: ${result.skill_id}`);
    } catch (error: any) {
      setSaveStatus('error');
      setTestLogs(`❌ 保存失败: ${error.message}`);
    } finally {
      setIsSaving(false);
    }
  };

  // 保存并提交审核
  const handleSubmit = async () => {
    if (!sessionId || !skillDraft.script_code) return;

    setIsSaving(true);
    setSaveStatus('idle');

    try {
      const result = await forgeSessionApi.submitSkill(sessionId);
      setSaveStatus('success');
      setTestLogs(`✅ 技能已提交审核！ID: ${result.skill_id}`);
    } catch (error: any) {
      setSaveStatus('error');
      setTestLogs(`❌ 提交失败: ${error.message}`);
    } finally {
      setIsSaving(false);
    }
  };

  const hasCode = Boolean(skillDraft.script_code);

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* 基本信息编辑 */}
      <div className="p-4 border-b border-neutral-800 bg-neutral-900/30">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="text-xs text-neutral-500 mb-1 block">技能名称</label>
            <input
              type="text"
              value={skillDraft.name}
              onChange={(e) => updateSkillDraft({ name: e.target.value })}
              placeholder="输入技能名称..."
              className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-1.5 text-sm text-white focus:border-blue-500 focus:outline-none"
            />
          </div>
          <div>
            <label className="text-xs text-neutral-500 mb-1 block">执行器类型</label>
            <select
              value={executorType}
              onChange={(e) => setExecutorType(e.target.value as any)}
              className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-1.5 text-sm text-white focus:border-blue-500 focus:outline-none"
            >
              {EXECUTOR_TYPES.map(type => (
                <option key={type.value} value={type.value}>{type.label}</option>
              ))}
            </select>
          </div>
        </div>
        <div className="mt-3">
          <label className="text-xs text-neutral-500 mb-1 block">技能描述</label>
          <input
            type="text"
            value={skillDraft.description}
            onChange={(e) => updateSkillDraft({ description: e.target.value })}
            placeholder="一句话描述技能功能..."
            className="w-full bg-neutral-800 border border-neutral-700 rounded-lg px-3 py-1.5 text-sm text-white focus:border-blue-500 focus:outline-none"
          />
        </div>
      </div>

      {/* 代码编辑器 */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <div className="h-10 bg-neutral-900 flex items-center justify-between px-4 border-b border-neutral-800">
          <div className="flex items-center gap-2">
            <Code size={14} className="text-yellow-500" />
            <span className="text-xs text-neutral-400">
              {executorType === 'Logical_Blueprint' ? 'process.nf' : 'main.py / main.R'}
            </span>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleTest}
              disabled={isTesting || !hasCode}
              className="flex items-center gap-1 px-3 py-1 text-xs bg-purple-600 hover:bg-purple-500 disabled:bg-neutral-800 disabled:text-neutral-500 text-white rounded-lg transition-colors"
            >
              <Play size={12} />
              {isTesting ? '测试中...' : '沙箱测试'}
            </button>
          </div>
        </div>

        <textarea
          value={executorType === 'Logical_Blueprint' ? (skillDraft.nextflow_code || '') : skillDraft.script_code}
          onChange={(e) => updateSkillDraft(
            executorType === 'Logical_Blueprint'
              ? { nextflow_code: e.target.value }
              : { script_code: e.target.value }
          )}
          placeholder="AI 生成的代码将显示在这里..."
          className="flex-1 bg-neutral-900 text-green-400 font-mono text-sm p-4 focus:outline-none resize-none leading-relaxed"
          spellCheck={false}
        />
      </div>

      {/* 参数 Schema 预览 */}
      {Object.keys(skillDraft.parameters_schema?.properties || {}).length > 0 && (
        <div className="border-t border-neutral-800 p-3 max-h-32 overflow-y-auto bg-neutral-900/30">
          <label className="text-xs text-neutral-500 mb-1 block flex items-center gap-2">
            <FileJson size={14} />
            参数 Schema
          </label>
          <pre className="text-xs text-emerald-400 font-mono whitespace-pre-wrap">
            {JSON.stringify(skillDraft.parameters_schema, null, 2)}
          </pre>
        </div>
      )}

      {/* 测试日志 */}
      {testLogs && (
        <div className="h-28 border-t border-neutral-800 p-3 bg-black overflow-y-auto">
          <pre className="text-xs text-emerald-400 font-mono whitespace-pre-wrap">{testLogs}</pre>
        </div>
      )}

      {/* 底部操作按钮 */}
      <div className="p-3 border-t border-neutral-800 flex gap-2">
        <button
          onClick={handleSaveOnly}
          disabled={isSaving || !hasCode}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-neutral-700 hover:bg-neutral-600 disabled:bg-neutral-800 disabled:text-neutral-500 text-white text-sm rounded-lg transition-colors"
        >
          <Save size={16} />
          保存为私有
        </button>
        <button
          onClick={handleSubmit}
          disabled={isSaving || !hasCode}
          className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 disabled:bg-neutral-800 disabled:text-neutral-500 text-white text-sm rounded-lg transition-colors"
        >
          <Send size={16} />
          保存并提交审核
        </button>
      </div>

      {/* 状态提示 */}
      {saveStatus === 'success' && (
        <div className="absolute top-2 right-2 bg-emerald-500/20 text-emerald-400 px-3 py-1 rounded-lg text-xs flex items-center gap-1">
          <Check size={14} /> 保存成功
        </div>
      )}
      {saveStatus === 'error' && (
        <div className="absolute top-2 right-2 bg-red-500/20 text-red-400 px-3 py-1 rounded-lg text-xs flex items-center gap-1">
          <AlertTriangle size={14} /> 保存失败
        </div>
      )}
    </div>
  );
}