/**
 * 增强版测试面板
 *
 * 功能：
 * 1. 实时 SSE 日志流式显示
 * 2. 执行进度和状态指示器
 * 3. 输出文件预览（表格、图片）
 * 4. 停止/重试控制
 * 5. 测试数据生成选项
 */

'use client';

import React, { useState, useRef, useCallback } from 'react';
import { Play, Square, RefreshCw, Settings, CheckCircle, XCircle, Clock, Cpu, Database } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

import { LogViewer, LogEntry, createLogEntry } from './LogViewer';
import { OutputPreview, OutputFile } from './OutputPreview';
import { skillForgeApi } from '@/lib/api';
import { ExecutorType } from '@/store/useForgeStore';

// 测试状态
type TestStatus = 'idle' | 'running' | 'success' | 'failed' | 'timeout';

// 根据文件扩展名判断类型
const getFileType = (filename: string): OutputFile['type'] => {
  const ext = filename.toLowerCase().split('.').pop();

  if (['tsv', 'csv', 'xls', 'xlsx'].includes(ext || '')) return 'table';
  if (['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'].includes(ext || '')) return 'image';
  if (['pdf'].includes(ext || '')) return 'pdf';
  if (['txt', 'md', 'json', 'yaml', 'yml', 'log'].includes(ext || '')) return 'text';

  return 'other';
};

// 执行统计
interface ExecutionStats {
  duration: number; // 秒
  memoryUsage?: string;
  cpuUsage?: string;
}

interface TestPanelProps {
  scriptCode: string;
  parametersSchema: Record<string, any>;
  executorType: ExecutorType;
  onTestComplete?: (result: any) => void;
  onCodeUpdate?: (newCode: string) => void;
  disabled?: boolean;
}

export function TestPanel({
  scriptCode,
  parametersSchema,
  executorType,
  onTestComplete,
  onCodeUpdate,
  disabled = false
}: TestPanelProps) {
  // 状态
  const [status, setStatus] = useState<TestStatus>('idle');
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [outputs, setOutputs] = useState<OutputFile[]>([]);
  const [stats, setStats] = useState<ExecutionStats | null>(null);
  const [showSettings, setShowSettings] = useState(false);
  const [autoGenerateData, setAutoGenerateData] = useState(true);
  const [maxTestRounds, setMaxTestRounds] = useState(3);

  // 中止控制器
  const abortControllerRef = useRef<AbortController | null>(null);

  // 添加日志
  const addLog = useCallback((level: LogEntry['level'], message: string) => {
    setLogs(prev => [...prev, createLogEntry(level, message)]);
  }, []);

  // 开始测试
  const handleStartTest = async () => {
    if (!scriptCode.trim()) {
      addLog('error', '没有代码可测试');
      return;
    }

    // 重置状态
    setStatus('running');
    setLogs([]);
    setOutputs([]);
    setStats(null);

    // 创建中止控制器
    abortControllerRef.current = new AbortController();

    addLog('system', '🚀 启动沙箱测试...');
    addLog('info', `执行器类型: ${executorType}`);
    addLog('info', `自动生成数据: ${autoGenerateData ? '是' : '否'}`);

    const startTime = Date.now();

    try {
      // 使用 SSE 流式测试 API
      await skillForgeApi.testDraftSkillStream(
        {
          scriptCode,
          parametersSchema,
          autoGenerateData,
          maxTestRounds,
          executorType
        },
        // 日志回调
        (message) => {
          // 根据消息内容判断日志级别
          const level: LogEntry['level'] =
            message.includes('❌') || message.includes('错误') || message.includes('失败') ? 'error' :
            message.includes('✅') || message.includes('成功') || message.includes('完成') ? 'success' :
            message.includes('⚠️') || message.includes('警告') ? 'warning' :
            'info';
          addLog(level, message);
        },
        // 状态回调
        (statusMsg) => {
          addLog('system', `[状态] ${statusMsg}`);
        },
        // 结果回调
        (result) => {
          // 处理测试结果
          if (result.outputs && Array.isArray(result.outputs)) {
            const outputFiles: OutputFile[] = result.outputs.map((out: any) => ({
              name: out.name || out.split('/').pop(),
              path: out.path || out,
              type: getFileType(out.name || out.split('/').pop()),
              size: out.size,
              preview: out.preview
            }));
            setOutputs(outputFiles);
          }

          // 如果 AI 修复了代码
          if (result.final_code && result.final_code !== scriptCode) {
            addLog('success', '🤖 代码已自动修复');
            onCodeUpdate?.(result.final_code);
          }

          setStats({
            duration: Math.round((Date.now() - startTime) / 1000),
            memoryUsage: result.memory_usage,
            cpuUsage: result.cpu_usage
          });
        },
        // 中止信号
        abortControllerRef.current.signal
      );

      // 测试完成
      const duration = Math.round((Date.now() - startTime) / 1000);
      setStats(prev => prev || { duration });

      setStatus('success');
      addLog('success', `✅ 测试完成！耗时 ${duration} 秒`);

      // 调用完成回调
      onTestComplete?.({ success: true, outputs, duration });
    } catch (error: any) {
      if (error.name === 'AbortError') {
        setStatus('idle');
        addLog('warning', '⚠️ 测试已取消');
      } else {
        setStatus('failed');
        addLog('error', `❌ 测试失败: ${error.message}`);
        onTestComplete?.({ success: false, error: error.message });
      }
    } finally {
      abortControllerRef.current = null;
    }
  };

  // 停止测试
  const handleStopTest = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      addLog('warning', '正在停止测试...');
    }
  };

  // 重新测试
  const handleRetry = () => {
    handleStartTest();
  };

  // 清除日志
  const handleClearLogs = () => {
    setLogs([]);
    setOutputs([]);
    setStats(null);
    setStatus('idle');
  };

  return (
    <div className="border border-neutral-800 rounded-lg bg-neutral-900/50 overflow-hidden">
      {/* 标题栏 */}
      <div className="flex items-center justify-between p-3 bg-neutral-800/50 border-b border-neutral-800">
        <div className="flex items-center gap-2">
          <div className={`w-2 h-2 rounded-full ${
            status === 'running' ? 'bg-blue-500 animate-pulse' :
            status === 'success' ? 'bg-emerald-500' :
            status === 'failed' ? 'bg-red-500' :
            'bg-neutral-600'
          }`} />
          <span className="text-sm font-medium text-white">测试验证</span>
          <StatusBadge status={status} />
        </div>

        <div className="flex items-center gap-2">
          {/* 设置按钮 */}
          <button
            onClick={() => setShowSettings(!showSettings)}
            className={`p-1.5 rounded transition-colors ${
              showSettings ? 'bg-neutral-700 text-white' : 'text-neutral-400 hover:text-white'
            }`}
          >
            <Settings size={14} />
          </button>
        </div>
      </div>

      {/* 设置面板 */}
      <AnimatePresence>
        {showSettings && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="border-b border-neutral-800 overflow-hidden"
          >
            <div className="p-3 space-y-3 bg-neutral-800/30">
              <div className="flex items-center justify-between">
                <label className="text-xs text-neutral-400">自动生成测试数据</label>
                <button
                  onClick={() => setAutoGenerateData(!autoGenerateData)}
                  className={`w-10 h-5 rounded-full transition-colors ${
                    autoGenerateData ? 'bg-blue-500' : 'bg-neutral-700'
                  }`}
                >
                  <div className={`w-4 h-4 bg-white rounded-full transition-transform ${
                    autoGenerateData ? 'translate-x-5' : 'translate-x-0.5'
                  }`} />
                </button>
              </div>
              <div className="flex items-center justify-between">
                <label className="text-xs text-neutral-400">最大测试轮数</label>
                <select
                  value={maxTestRounds}
                  onChange={(e) => setMaxTestRounds(Number(e.target.value))}
                  className="bg-neutral-800 border border-neutral-700 rounded px-2 py-1 text-xs text-white"
                >
                  <option value={1}>1 轮</option>
                  <option value={3}>3 轮</option>
                  <option value={5}>5 轮</option>
                </select>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* 控制按钮 */}
      <div className="p-3 border-b border-neutral-800">
        <div className="flex items-center gap-2">
          {status !== 'running' ? (
            <button
              onClick={handleStartTest}
              disabled={disabled || !scriptCode.trim()}
              className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-purple-600 hover:bg-purple-500 disabled:bg-neutral-800 disabled:text-neutral-500 text-white text-sm rounded-lg transition-colors"
            >
              <Play size={14} />
              {status === 'failed' ? '重新测试' : '沙箱测试'}
            </button>
          ) : (
            <button
              onClick={handleStopTest}
              className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-red-600 hover:bg-red-500 text-white text-sm rounded-lg transition-colors"
            >
              <Square size={14} />
              停止测试
            </button>
          )}

          {logs.length > 0 && status !== 'running' && (
            <button
              onClick={handleClearLogs}
              className="flex items-center gap-1 px-3 py-2 bg-neutral-700 hover:bg-neutral-600 text-white text-sm rounded-lg transition-colors"
            >
              <RefreshCw size={14} />
              清除
            </button>
          )}
        </div>
      </div>

      {/* 执行统计 */}
      {stats && (
        <div className="flex items-center gap-4 px-3 py-2 bg-neutral-800/30 border-b border-neutral-800 text-xs text-neutral-400">
          <div className="flex items-center gap-1">
            <Clock size={12} />
            <span>{stats.duration} 秒</span>
          </div>
          {stats.memoryUsage && (
            <div className="flex items-center gap-1">
              <Database size={12} />
              <span>{stats.memoryUsage}</span>
            </div>
          )}
          {stats.cpuUsage && (
            <div className="flex items-center gap-1">
              <Cpu size={12} />
              <span>{stats.cpuUsage}</span>
            </div>
          )}
        </div>
      )}

      {/* 日志区域 */}
      <LogViewer
        logs={logs}
        isStreaming={status === 'running'}
        maxHeight="200px"
      />

      {/* 输出文件预览 */}
      {outputs.length > 0 && (
        <div className="border-t border-neutral-800 p-3">
          <div className="text-xs text-neutral-500 mb-2 flex items-center gap-1">
            <CheckCircle size={12} />
            输出文件 ({outputs.length})
          </div>
          <OutputPreview outputs={outputs} />
        </div>
      )}
    </div>
  );
}

// 状态徽章组件
function StatusBadge({ status }: { status: TestStatus }) {
  if (status === 'idle') return null;

  const config = {
    running: { icon: <Clock size={12} />, text: '执行中', className: 'text-blue-400 bg-blue-500/20' },
    success: { icon: <CheckCircle size={12} />, text: '成功', className: 'text-emerald-400 bg-emerald-500/20' },
    failed: { icon: <XCircle size={12} />, text: '失败', className: 'text-red-400 bg-red-500/20' },
    timeout: { icon: <Clock size={12} />, text: '超时', className: 'text-yellow-400 bg-yellow-500/20' }
  };

  const { icon, text, className } = config[status];

  return (
    <span className={`flex items-center gap-1 px-2 py-0.5 rounded text-xs ${className}`}>
      {icon}
      {text}
    </span>
  );
}

// 导出子组件
export { LogViewer, OutputPreview };