import os
import uuid
try:
    import markdown
except ImportError:
    markdown = None
from datetime import datetime
from langchain_core.tools import tool
from app.core.config import settings
from app.core.logger import log
import uuid
import markdown
from datetime import datetime
from langchain_core.tools import tool
from app.core.config import settings
from app.core.logger import log


@tool
def generate_publishable_report(title: str, full_markdown_content: str, project_id: int) -> str:
    """
    【极度重要】当整个分析流程（包括查文献、清洗、画图、解释）全部结束后，由报告撰写专家调用此工具！
    它将 Markdown 格式的报告渲染成排版精美的学术级 HTML 报告，并存入系统。
    
    参数要求：
    - title: 报告的精炼标题（如：结直肠癌单细胞免疫微环境差异分析报告）
    - full_markdown_content: 包含【摘要】、【背景】、【方法学（包括使用的镜像和参数）】、【结果（必须包含已生成的图片链接）】、【结论】和【参考文献】的完整 Markdown 文本。
    - project_id: 当前的项目ID
    """
    log.info(f"📄 正在为项目 {project_id} 生成可发表级学术报告...")
    
    try:
        # 将 Markdown 转换为 HTML，开启表格和代码高亮支持
        html_body = markdown.markdown(
            full_markdown_content,
            extensions=['tables', 'fenced_code', 'toc']
        )
        
        # ✨ 学术级 CSS 模板引擎 (带有完美的打印支持 @media print)
        academic_template = f"""
        <!DOCTYPE html>
        <html lang="zh-CN">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{title}</title>
            <style>
                :root {{ --primary-color: #2c3e50; --text-color: #333; --border-color: #e2e8f0; }}
                body {{ 
                    font-family: "Palatino Linotype", "Times New Roman", Times, serif; 
                    line-height: 1.8; color: var(--text-color); background: #f8fafc; margin: 0; padding: 40px 20px; 
                }}
                .paper-container {{
                    max-width: 900px; margin: 0 auto; background: #fff; padding: 60px 80px;
                    box-shadow: 0 10px 25px rgba(0,0,0,0.05); border-radius: 8px;
                }}
                h1 {{ text-align: center; font-size: 2.2em; color: var(--primary-color); border-bottom: 2px solid var(--primary-color); padding-bottom: 15px; margin-bottom: 10px; }}
                h2 {{ color: var(--primary-color); margin-top: 40px; font-size: 1.5em; border-bottom: 1px solid var(--border-color); padding-bottom: 8px; }}
                h3 {{ color: #475569; margin-top: 30px; font-size: 1.2em; }}
                .meta-info {{ text-align: center; color: #64748b; font-style: italic; font-size: 0.95em; margin-bottom: 50px; font-family: sans-serif; }}
                img {{ max-width: 100%; height: auto; display: block; margin: 30px auto; border: 1px solid var(--border-color); border-radius: 4px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }}
                table {{ width: 100%; border-collapse: collapse; margin: 30px 0; font-family: sans-serif; font-size: 0.9em; }}
                th, td {{ padding: 12px 15px; border-bottom: 1px solid var(--border-color); text-align: left; }}
                th {{ background-color: #f1f5f9; font-weight: 600; color: var(--primary-color); border-top: 2px solid var(--primary-color); border-bottom: 2px solid var(--primary-color); }}
                blockquote {{ border-left: 4px solid #cbd5e1; margin: 0; padding-left: 20px; color: #64748b; font-style: italic; }}
                .print-btn {{ display: block; width: 200px; margin: 0 auto 30px; padding: 12px; background: #2563eb; color: white; text-align: center; border-radius: 6px; cursor: pointer; font-family: sans-serif; font-weight: bold; transition: background 0.3s; box-shadow: 0 4px 6px rgba(37,99,235,0.2); }}
                .print-btn:hover {{ background: #1d4ed8; }}
                
                @media print {{
                    body {{ background: #fff; padding: 0; }}
                    .paper-container {{ box-shadow: none; padding: 0; max-width: 100%; margin: 0; }}
                    .print-btn {{ display: none; }}
                    @page {{ margin: 2.5cm; }}
                }}
            </style>
        </head>
        <body>
            <div class="paper-container">
                <div class="print-btn no-print" onclick="window.print()">🖨️ 导出为 PDF (Print)</div>
                <h1>{title}</h1>
                <div class="meta-info">
                    Generated by Autonome Studio Multi-Agent Team<br>
                    Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Project ID: {project_id}
                </div>
                <div class="content">
                    {html_body}
                </div>
            </div>
        </body>
        </html>
        """

        # 确保目录存在
        os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
        
        # 物理保存文件
        file_uuid = str(uuid.uuid4())[:8]
        filename = f"report_p{project_id}_{file_uuid}.html"
        file_path = os.path.join(settings.UPLOAD_DIR, filename)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(academic_template)
            
        report_url = f"http://localhost:8000/uploads/{filename}"
        
        return f"""
        ✅ 报告已成功渲染并物理落盘！
        文件路径：{file_path}
        访问链接：{report_url}
        
        请直接向用户回复："🎉 **分析报告已就绪！** 您的全套分析流程已经由团队整理完毕。请点击此处查看或导出 PDF：[👉 查看学术级报告]({report_url})"
        """
        
    except Exception as e:
        log.error(f"报告生成失败: {str(e)}")
        return f"❌ 报告生成引擎报错: {str(e)}"
